# Generated by Django 4.0.4 on 2022-05-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'VN__USER', 'verbose_name_plural': 'VN__USERS'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='login',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='HT__EMAIL', max_length=50, unique=True, verbose_name='VN__EMAIL'),
        ),
    ]
