# Generated by Django 4.0.4 on 2022-05-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(help_text='HT__CONTENT', verbose_name='VN__CONTENT'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='HT__TITLE', max_length=255, verbose_name='VN__TITLE'),
        ),
    ]
