# Generated by Django 4.0.4 on 2022-05-11 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_post_content_alter_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(default='', help_text='HT__STATUS', max_length=10, verbose_name='VN__STATUS'),
            preserve_default=False,
        ),
    ]
