# Generated by Django 4.0.4 on 2022-05-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], help_text='HT__STATUS', max_length=10, verbose_name='VN__STATUS'),
        ),
    ]
